config/routes.rb
Rails.application.routes.draw do
  resources :posts, param: :slug do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
    get 'edit-profile', to: 'devise/registrations#edit', as: :edit_profile
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
  end

  root :to => 'pages#index'
  get 'my-news', to: "pages#my_news", :as => :user_root
  get 'change-password', to: 'passwords#edit', as: :change_password
  patch 'update-password', to: 'passwords#update', as: :update_password
end

app/views/shared/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <div class="u-container">
    <ul class="breadcrumbs-list">
      <li class="breadcrumbs-item">
        <%= link_to "HOME", root_path, class: "breadcrumbs-link" %>
      </li>
      <% if locals[:link].present? %>
        <li class="breadcrumbs-item">
          <%= link_to locals[:title], locals[:link], class: "breadcrumbs-link" %>
        </li>
      <% else %>
        <li class="breadcrumbs-item">
          <%= locals[:title] %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-inner">
    <div class="u-container footer-inner-content">
      <div class="footer-logo">
        <%= image_tag(asset_path('logo-white.png'), alt:'BLOG', class: "footer-logo-image") %>
      </div>
      <div class="footer-description">
        <p class="footer-text">
          サンプルテキストサンプル ルテキストサンプルテキストサ
        </p>
        <p class="footer-text">ンプルテキストサンプル ルテキスト</p>
      </div>
      <div class="footer-back-to-top">
        <div class="footer-back-to-top-arrow"></div>
        <div class="footer-back-to-top-text">
          <%= link_to 'TOP', '#top' %>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="u-container">
      <p class="footer-copyright-text">Copyright©2007-2019 Blog Inc.</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="u-container">
    <div class="header-inner">
      <%= link_to root_path, class:"header-logo" do %>
        <%= image_tag(asset_path('logo-black.png'), alt:'BLOG', class: "header-logo-image") %>
      <% end %>

      <%= render "/shared/nav" %>
    </div>
  </div>

  <div class="u-container">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
  </div>
</header>

app/views/shared/_nav.html.erb
<nav class="nav">
  <ul class="nav-list">
    <% if !user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sign In', sign_in_path, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'My News', user_root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Profile', edit_profile_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Change Password", change_password_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', method: :delete %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_news.html.erb
<div class="posts-content">
  <div class="posts-body">
    <ul class="posts-list" id="posts-list">
      <% obj.each_with_index do |post,index| %>
        <li class="posts-item" <% if index > 7 %> style="display:none;" <% end %>>
          <a class="posts-link" href="<%= post_path(post) %>">
            <div class="posts-image-wrapper">
              <div class="posts-image" style="background-image: url('<%= cl_image_path(post.photo_upload) %>');">
              </div>
            </div>
            <div class="posts-item-header">
              <time datetime="<%= post.created_at.strftime("%Y.%m.%d") %>" class="posts-created"><%= post.created_at.strftime("%Y.%m.%d") %></time>
              <div class="posts-comments"><%= post.comments.count %></div>
            </div>
            <p class="posts-text"><%= post.title %></p>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="posts-footer">
    <% if obj.count > 8 %>
      <button id="load-more" class="posts-loadmore-button">LOAD MORE</button>
      <input id="load-counter" type="hidden" value="0">
    <% end %>
  </div>
</div>

<script language="javascript">
  document.getElementById("load-more").addEventListener("click", function(event) {
    console.log('Load more trigger!');
    loadMore();
  });

  function loadMore() {
    // Number of posts to display
    var postGrouping = 8;
    var postChildren = document.getElementById("posts-list").children;

    // Load counter for number of time LOAD MORE is triggered
    var loadCounter = parseInt(document.getElementById('load-counter').value);
    loadCounter = isNaN(loadCounter) ? 0 : loadCounter;
    loadCounter++;

    // Set variable for start/end in showing more posts
    var start = (loadCounter * postGrouping) + 1;
    var end = start + postGrouping;

    // Process only if valid range
    if (start < postChildren.length) {
      var i;
      for (i = start; i < end; i++) {
        console.log(postChildren[i]);
        if (postChildren[i]) {
          postChildren[i].style.display = 'block';
        }
      }

      // Update load counter for reference later
      document.getElementById("load-counter").value = loadCounter;

      // Hide Load more if already reach the max number of posts
      if (end >= postChildren.length) {
        document.getElementById("load-more").style.display = "none";
      }
    }
  }
</script>

app/views/shared/_slider.html.erb
<div class="carousel">
  <div class="carousel-indicator">
    <% obj.each_with_index do |post, index| %>
      <div class="carousel-indicator-item <%= (index == 0) ? 'is-active' : '' %>" onclick="currentSlide(<%= index+1 %>)"></div>
    <% end %>
  </div>
  <div class="carousel-slides">
    <div class="carousel-navigate carousel-navigate-left" id="prev" onclick="plusSlides(-1)">
      <div class="navigate navigate-left">
      </div>
    </div>
    <% obj.each do |post| %>
      <div class="carousel-list" style="margin-left: 0px;">
        <div class="carousel-item fade" style="background-image: url('<%= cl_image_path(post.photo_upload, :width => 545, :crop => "pad") %>');">
          <div class="u-container carousel-item-inner-wrapper">
            <div class="carousel-item-inner">
              <div class="carousel-item-title"><%= truncate(post.description, length: 50) %></div>
              <time datetime="<%= post.created_at.strftime("%Y.%m.%d") %>" class="carousel-item-created"><%= post.created_at.strftime("%Y.%m.%d") %></time>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="carousel-navigate carousel-navigate-right" id="next" onclick="plusSlides(1)">
      <div class="navigate navigate-right">
      </div>
    </div>
  </div>
</div>

<script>
  var slideIndex = 1;
  showSlides(slideIndex);

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("carousel-list");
    var dots = document.getElementsByClassName("carousel-indicator-item");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" is-active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " is-active";
  }
</script>