config/routes.rb
Rails.application.routes.draw do
  resources :posts, param: :slug do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
    get 'edit-profile', to: 'devise/registrations#edit', as: :edit_profile
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
  end

  root :to => 'pages#index'
  get 'my-news', to: "pages#my_news", :as => :user_root
  get 'change-password', to: 'passwords#edit', as: :change_password
  patch 'update-password', to: 'passwords#update', as: :update_password
end

app/models/post.rb
class Post < ApplicationRecord
  after_validation :set_slug, only: %i[create update]
  after_validation :set_photo_upload, only: %i[create update]
  acts_as_paranoid
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  scope :published, -> { where(published: true) }

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = [title.to_s.parameterize].join("-")
  end

  def set_photo_upload
    self.photo_upload = "h60c1tudxdnldlp6hqt4.png" if photo_upload.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]
  before_action :set_commentable, only: %i[show]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :cloudinary_upload, only: %i[create update]

  # GET /posts or /posts.json
  def index
    redirect_to user_root_path
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.photo_upload = @uploaded["url"] unless @uploaded.nil?

    if @post.save
      flash[:notice] = "Post was successfully created."
      redirect_to edit_post_path(@post)
    else
      render "new"
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    new_params = post_params
    new_params[:photo_upload] = @uploaded["url"] unless @uploaded.nil?

    if @post.update(new_params)
      flash[:notice] = "Post was successfully updated."
      redirect_to edit_post_path(@post)
    else
      render "edit"
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by(slug: params[:slug])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :published, :photo_upload, :keywords)
  end

  # For polymorphic comments
  def set_commentable
    @commentable = Post.find_by(slug: params[:slug])
  end

  # Edit/delete post restriction
  def require_same_user
    @post = current_user.posts.find_by(slug: params[:slug])
  end

  def cloudinary_upload
    return unless post_params[:photo_upload]

    @uploaded = Cloudinary::Uploader.upload(post_params[:photo_upload])
  end
end

app/views/posts/_form.html.erb
<div class="u-container">
  <%= simple_form_for obj, html: { multipart: true, class: "post-form-inner" } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="post-header post-form-header">
      <% if obj.id %>
        <h1><%= title "Edit Post" %></h1>
        <ul class="post-action-list post-form-action-list">
          <li class="post-action-item">
            <button type="submit" class="post-action-link post-form-action-button">Save Post</button>
          </li>

          <li class="post-action-item">
            <%= link_to 'Delete', obj, class: "post-action-link", method: :delete %>
          </li>

          <li class="post-action-item">
            <%= link_to 'Cancel', obj, class: "post-action-link" %>
          </li>
        </ul>
      <% else %>
        <h1><%= title "New Post" %></h1>
        <ul class="post-action-list post-form-action-list">
          <li class="post-action-item">
            <button type="submit" class="post-action-link post-form-action-button">Create Post</button>
          </li>

          <li class="post-action-item">
            <%= link_to 'Cancel', user_root_path, class: "post-action-link" %>
          </li>
        </ul>
      <% end %>
    </div>

    <div class="post-body">
      <div class="post-form-body-top">
        <time datetime="<%= DateTime.current.to_date %>" class="post-created"><%= DateTime.current.to_date %></time>
        <div class="post-form-published">
          <%= f.input :published, label: false, input_html: { class: 'post-form-published-checkbox' } %>
          <%= f.label :published, label: 'Publish', class: 'post-form-published-label' %>
        </div>
      </div>
      <%= f.input :title, as: :text, label: false, placeholder: 'Title',
                  input_html: { class: 'post-form-title-textarea' },
                  wrapper_html: { class: 'post-form-title' } %>
      <div id="preview-image" class="post-form-image-wrapper" style="background-image: url('<%= cl_image_path(obj.id ? obj.photo_upload : 'h60c1tudxdnldlp6hqt4.png', :width => 755, :crop => "pad") %>')">
        <label for="photo_upload" class="post-form-image-label" id="upload-image">UPLOAD IMAGE
          <%= f.input :photo_upload, as: :file, label: false, input_html: { style: "display: none;", id: "photo-upload" } %>
        </label>
      </div>
      <%= f.input :description, label: false, placeholder: 'Content',
                  input_html: { class: 'post-form-content-textarea' },
                  wrapper_html: { class: 'post-form-text-content' } %>
      <%= f.input :keywords, as: :text, label: false, placeholder: 'Keywords',
                  input_html: { class: 'post-form-keywords-textarea' },
                  wrapper_html: { class: 'post-form-keywords' } %>
    </div>
  <% end %>
  <br>
</div>

app/views/posts/edit.html.erb
<% set_meta_tags description: @post.description, keywords: @post.keywords %>

<%= render "shared/breadcrumbs", locals: { title: @post.title, link: post_path(@post) }  %>

<%= render "form", obj: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% set_meta_tags description: "New post page.", keywords: "Blog, New post" %>

<%= render "shared/breadcrumbs", locals: { title: "New Post" }  %>

<%= render "form", obj: @post %>

app/views/posts/show.html.erb
<% set_meta_tags description: @post.description,
                 keywords: @post.keywords,
                 image_src: cl_image_path(@post.photo_upload),
                 og: {
                   image: :image_src
                 } %>

<%= render "shared/breadcrumbs", locals: { title: @post.title }  %>

<div class="u-container">
  <% if current_user == @post.user %>
    <div class="post-header">
      <ul class="post-action-list">
        <li class="post-action-item">
          <%= link_to 'Edit Post', edit_post_path(@post), class: "post-action-link" %>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="post-body">
    <time datetime="<%= @post.created_at.strftime("%Y.%m.%d") %>" class="post-created"><%= @post.created_at.strftime("%Y.%m.%d") %></time>
    <h1 class="post-title"><%= title @post.title %></h1>
    <div class="post-image" style="background-image: url('<%= cl_image_path(@post.photo_upload, :width => 755, :crop => "pad") %>')";></div>
    <div class="post-text">
      <%= @post.description %>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="comment">
      <div class="u-container">
        <%= render "comments/comments", locals: { commentable: @post } %>
        <%= render "comments/form", locals: { commentable: @post } %>
      </div>
    </div>
  <% end %>
</div>